[workspace]

members = [
    "attribution",
    "attribution-examples/ez-trace/ez-trace-macros",
    "attribution-examples/ez-trace/fibonacci",
    "attribution-examples/exhaustive-attr/exhaustive-attr",
    "attribution-examples/exhaustive-attr/exhaustive-attr-macros",
    "attribution-macros"
]