[package]
name = "ez-trace-macros"
version = "0.1.0"
authors = ["Timothy Flowers <t_chuck_flowers@yahoo.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
attribution = { path = "../../../attribution" }
proc-macro2 = "^1.0.0"
quote = "^1.0.0"
syn = "^1.0.0"
