[package]
name = "exhaustive-attr"
version = "0.1.0"
authors = ["Timothy Flowers <t_chuck_flowers@yahoo.com>"]
edition = "2018"

[dependencies]
exhaustive-attr-macros = { path = "../exhaustive-attr-macros" }