[package]
name = "attribution"
version = "0.1.0"
authors = ["Timothy Flowers <t_chuck_flowers@yahoo.com>"]
edition = "2018"
repository = "https://github.com/chuck-flowers/attribution"

[dependencies]
attribution-macros = { path = "../attribution-macros" }
proc-macro2 = "0.4.30"
syn = "0.15.41"