[package]
name = "attribution"
version = "0.1.0"
authors = ["Timothy Flowers <t_chuck_flowers@yahoo.com>"]
edition = "2018"

[dependencies]
attribution-macros = { path = "../attribution-macros" }
attribution-types = { path = "../attribution-types" }